### ISSUE TITLE
Não funcionou

### ISSUE THREAD

**Issue by viniciusperson** [felipeyousoro/CEO-do-MIPS#1]
Meu processador derreteu quando tentei rodar, logo em seguida tive um avc e a fiação de casa entrou em combustão.

**Comment by felipeyousoro** [comment]
KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK baixa o mars simulator e roda

**Comment by felipeyousoro** [comment]
VAI TOMAR NO CU CAMELOFON
